"""create job_records and audit_logs

Revision ID: bcc6f4a62b17
Revises: 
Create Date: 2026-05-21 16:41:32.285172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc6f4a62b17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_job_id'), 'audit_logs', ['job_id'], unique=False)
    op.create_table('job_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tipo_declarado', sa.String(length=32), nullable=False),
    sa.Column('tipo_detectado', sa.String(length=32), nullable=True),
    sa.Column('tipo_confirmado', sa.Boolean(), nullable=True),
    sa.Column('numero_processo', sa.String(length=64), nullable=True),
    sa.Column('vara', sa.String(length=128), nullable=True),
    sa.Column('origem', sa.String(length=128), nullable=True),
    sa.Column('paginas', sa.Integer(), nullable=True),
    sa.Column('confianca_geral', sa.Float(), nullable=True),
    sa.Column('requer_revisao', sa.Boolean(), nullable=True),
    sa.Column('modelo_ia', sa.String(length=64), nullable=True),
    sa.Column('hash_arquivo', sa.String(length=80), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_records_job_id'), 'job_records', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_records_job_id'), table_name='job_records')
    op.drop_table('job_records')
    op.drop_index(op.f('ix_audit_logs_job_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
